RPCAL: size spn buffer large enough to hold any possible value
Found via new gcc8 warnings format-truncation warnings:

/home/jlayton/git/nfs-ganesha/src/RPCAL/gss_credcache.c: In function ‘find_keytab_entry’:
/home/jlayton/git/nfs-ganesha/src/RPCAL/gss_credcache.c:725:36: error: ‘%s’ directive output may be truncated writing up to 1024 bytes into a region of size 299 [-Werror=format-truncation=]
     snprintf(spn, sizeof(spn), "%s/%s@%s",
                                    ^~
       svcnames[j], myhostname, realm);
                    ~~~~~~~~~~
/home/jlayton/git/nfs-ganesha/src/RPCAL/gss_credcache.c:725:5: note: ‘snprintf’ output 3 or more bytes (assuming 1027) into a destination of size 300
     snprintf(spn, sizeof(spn), "%s/%s@%s",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       svcnames[j], myhostname, realm);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jlayton/git/nfs-ganesha/src/RPCAL/gss_credcache.c:716:33: error: ‘%s’ directive output may be truncated writing up to 1025 bytes into a region of size 300 [-Werror=format-truncation=]
     snprintf(spn, sizeof(spn), "%s@%s", myhostad,
                                 ^~      ~~~~~~~~
/home/jlayton/git/nfs-ganesha/src/RPCAL/gss_credcache.c:716:5: note: ‘snprintf’ output 2 or more bytes (assuming 1027) into a destination of size 300
     snprintf(spn, sizeof(spn), "%s@%s", myhostad,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       realm);
       ~~~~~~

Change-Id: I33d5ad90cb3300ce26580d4e374f5a216d609661
Signed-off-by: Jeff Layton <jlayton@redhat.com>
(cherry picked from commit 2e78a29b5e46e2c1252556d2b087ef819fb46320)